name: thekaamwale
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.16.1
  image_picker: ^1.1.0
  firebase_storage: ^11.7.2
  fluttertoast: ^8.2.5
  get: ^4.6.6
  multiselect_formfield: ^0.1.7
  url_launcher: ^6.2.6
  shimmer: ^3.0.0
  razorpay_flutter: ^1.3.6
  flutter_native_splash: ^2.4.0
  google_mobile_ads: ^5.1.0
  auto_size_text: ^3.0.0
  video_player: ^2.8.7
  chewie: ^1.8.1






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/

